// AUTH

export const AUTH_LOGIN_CHANGED = 'AUTH_LOGIN_CHANGED'
export const AUTH_PASSWORD_CHANGED = 'AUTH_PASSWORD_CHANGED'
export const AUTH_TRY_TO_AUTH = 'AUTH_TRY_TO_AUTH'
export const AUTH_PERFORM_AUTH = 'AUTH_PERFORM_AUTH'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_OK = 'AUTH_OK'
export const AUTH_CHECK = 'AUTH_CHECK'
export const AUTH_STOP_ACTIVITY = 'AUTH_STOP_ACTIVITY'


// INVS

export const INVS_LIST_GET = 'INVS_LIST_GET'
export const INVS_LIST_LOADING = 'INVS_LIST_LOADING'
export const INVS_LIST_SHOW = 'INVS_LIST_SHOW'

// INV
export const INV_SET = 'INV_SET'

// LINE

export const LINE_SHOW = 'LINE_SHOW'
export const LINE_TEXT_FIELD_CHANGED = 'LINE_TEXT_FIELD_CHANGED'
export const LINE_IMAGE_CAPTURED = 'LINE_IMAGE_CAPTURED'
export const LINE_MEDIA_DELETE = 'LINE_MEDIA_DELETE'
export const LINE_MEDIA_SET = 'LINE_MEDIA_SET'
export const LINE_MISSING_REQUIRED_FIELDS = 'LINE_MISSING_REQUIRED_FIELDS'
export const LINE_MISSING_REQUIRED_FIELDS_RESET = 'LINE_MISSING_REQUIRED_FIELDS_RESET'
export const LINE_SUCCESSFULLY_SAVED_RESET = 'LINE_SUCCESSFULLY_SAVED_RESET'
export const LINE_SUCCESSFULLY_SAVED = 'LINE_SUCCESSFULLY_SAVED'
export const LINE_ADD_ALERT_RESET = 'LINE_ADD_ALERT_RESET'
export const LINE_ADD_ALERT = 'LINE_ADD_ALERT'

// TASKS

export const TASKS_SET = 'TASKS_SET'
export const TASK_SET_CURRENT = 'TASK_SET_CURRENT'
export const TASK_TEXT_FIELD_CHANGED = 'TASK_TEXT_FIELD_CHANGED'
export const TASK_IMAGE_CAPTURED = 'TASK_IMAGE_CAPTURED'
export const TASK_MEDIA_SET = 'TASK_MEDIA_SET'
export const TASK_SUCCESSFULLY_SAVED_RESET = 'TASK_SUCCESSFULLY_SAVED_RESET'
export const TASK_SUCCESSFULLY_SAVED = 'TASK_SUCCESSFULLY_SAVED'