// AUTH

export const AUTH_LOGIN_CHANGED = 'AUTH_LOGIN_CHANGED'
export const AUTH_PASSWORD_CHANGED = 'AUTH_PASSWORD_CHANGED'
export const AUTH_TRY_TO_AUTH = 'AUTH_TRY_TO_AUTH'
export const AUTH_PERFORM_AUTH = 'AUTH_PERFORM_AUTH'