// AUTH

export const AUTH_LOGIN_CHANGED = 'AUTH_LOGIN_CHANGED'
export const AUTH_PASSWORD_CHANGED = 'AUTH_PASSWORD_CHANGED'
export const AUTH_TRY_TO_AUTH = 'AUTH_TRY_TO_AUTH'
export const AUTH_PERFORM_AUTH = 'AUTH_PERFORM_AUTH'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_OK = 'AUTH_OK'


// INVS

export const INVS_LIST_GET = 'INVS_LIST_GET'
export const INVS_LIST_LOADING = 'INVS_LIST_LOADING'
export const INVS_LIST_SHOW = 'INVS_LIST_SHOW'

// INV
export const INV_SET = 'INV_SET'

// LINE

export const LINE_SHOW = 'LINE_SHOW'
export const LINE_TEXT_FIELD_CHANGED = 'LINE_TEXT_FIELD_CHANGED'
export const LINE_IMAGE_CAPTURED = 'LINE_IMAGE_CAPTURED'